[component]
structures = [ "content_blocks" ]
label = "Contact Form"
description = "Generic contact form"
icon = "wysiwyg"
tags = ["Text"]

[props]
form_title = "Get in touch"
form_description = "Vonge comes with a built-in contact form."
form_success_page = "https://submit-form.com/RMltzEeL"
form_submission_email = "site@example.com" # Add your email for contact form
form_button_text = "Send now"
google_recaptcha_v2_site_key = "google_recaptcha_v2_site_key"