title: Deepisha Solanki
description:  My homepage - Here you will information about me, mostly professional, some personal.
social_media_share_image: /images/homepage_pic.jpeg
disqus-identifier:
google-analytics:
cv-path: /cv.pdf